spring.application.name=schedule-system
spring.datasource.url=jdbc:h2:file:./data/schedule-system;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.locations=classpath:db/migration/common
spring.thymeleaf.cache=false
