CREATE TABLE schedule_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    requester_name VARCHAR(100),
    work_type VARCHAR(30),
    request_detail TEXT,
    address VARCHAR(500),
    desired_arrival_time VARCHAR(100),
    companion_required BOOLEAN NOT NULL DEFAULT FALSE,
    meeting_place VARCHAR(300),
    departure_time TIME,
    vehicle_name VARCHAR(100),
    dispatch_status VARCHAR(30) NOT NULL DEFAULT 'UNANSWERED',
    note TEXT,
    entry_state VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
    draft_reason VARCHAR(30),
    draft_error_detail VARCHAR(500),
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_schedule_time_range
        CHECK (start_time IS NULL OR end_time IS NULL OR start_time < end_time),
    CONSTRAINT ck_schedule_entry_state
        CHECK (entry_state IN ('DRAFT', 'PUBLISHED')),
    CONSTRAINT ck_schedule_dispatch_status
        CHECK (dispatch_status IN ('UNANSWERED', 'REQUIRED', 'DISPATCHED')),
    CONSTRAINT ck_published_schedule_fields
        CHECK (
            entry_state <> 'PUBLISHED'
            OR (
                start_time IS NOT NULL
                AND end_time IS NOT NULL
                AND work_type IS NOT NULL
                AND (
                    work_type IN ('RECEIVING', 'PRODUCT_MANAGEMENT')
                    OR NULLIF(TRIM(requester_name), '') IS NOT NULL
                )
            )
        )
);

CREATE INDEX idx_schedule_requests_work_date
    ON schedule_requests (work_date);

CREATE INDEX idx_schedule_requests_entry_state
    ON schedule_requests (entry_state);
